  
#deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: nikithagullapalli/mmv3-currency-conversion-service-kubernetes:0.0.12-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv3-currency-conversion-service-kubernetes
        readinessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/liveness
        envFrom:
          - configMapRef:
              name: currrency-converstion
#        env:
#          - name: CURRENCY_EXCHANGE_URI
#            value: http://currency-exchange
      restartPolicy: Always
        
---

#service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer

---

#configmap
apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  name: currrency-converstion
  namespace: default
 